name: My Actions
on: push # or [push, pull_request]
jobs:
  job-1:
    name: First Job # display name
    runs-on: ubuntu-latest
    steps:
      - run: echo "The event name is ${{github.workspace}}."
      - run: ls ${{github.workspace}}
       
