name: My Actions
on: push # or [push, pull_request]
jobs:
  job-1:
    name: First Job # display name
    runs-on: ubuntu-latest
    steps:
      - run: echo "The event name is ${{github.workspace}}."
      - run: ls ${{github.workspace}}
      - name: conditional action
        if: ${{github.event_name == 'push'}}
        run: echo "Yes, it is!"
  job-2:
    name: Second Job
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - run: echo "This is the second job."
